SDK update to 2.1.0, removed deduplication of results, fixed bug with…
metalwarrior665/actor-indeed-scraper pull request #21
Opened 2021-12-08 20:11 UTC by OlehVeselov92

… the last LIST page

2021-12-08 20:20 UTC, metalwarrior665 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
Isn't there a way those pages are different or they are completely identical (which does not make sense)?

2021-12-08 20:40 UTC, OlehVeselov92 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
What do you mean by that?)
There are completely identical pages (URLs) in the list.
So, if we want to get  all 200 offers (that are shown on the list), we set uniqueKey.

2021-12-08 21:19 UTC, metalwarrior665 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
I am talking that maybe those URLs have some different parameters so we could use that instead of random number (that could bite us when resurrect happens, we will enqueue twice)

2021-12-08 21:27 UTC, OlehVeselov92 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
Understood.
You are right. Missed it. 
Will remove uniqueKey.

2021-12-08 21:33 UTC, OlehVeselov92 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
@metalwarrior665 Done. Thanks for catching my bug)

2021-12-08 22:37 UTC, metalwarrior665 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
Do you have examples of the URLs (from `makeUrlFull` or any from the page)? And how they differ for the duplicate pages?

2021-12-09 06:25 UTC, OlehVeselov92 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
Yeah, woke up and figured that I made mistake again)
Just rechecked everything.
Example of ITEM link: https://www.indeed.com/company/Allegion/jobs/Senior-Android-Engineer-32eca2e037ad21a5?fccid=31252cfea3db6240&vjs=3

And links can be repeated in the list, That's why I used Math.Random() to scrape all items.

So, what shall I do?

2021-12-09 06:32 UTC, OlehVeselov92 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
Actor is not that big (usually 500-700 requests), so it's not the case for resurrection I guess)

2021-12-13 09:25 UTC, petrpatek approved these changes
Great job figuring this out!

2021-12-13 09:25 UTC, petrpatek commented on src/main.js
> +                    const maxItemsOnSite = +$('#searchCountPages').text().trim().split('of')[1].trim().split(' ')[0];
This would probably deserve a comment.

2021-12-13 09:57 UTC, metalwarrior665 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
I want to look at this, it seems weird case and I would like to see better solution than Math.random()

2021-12-13 09:58 UTC, metalwarrior665 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
Do you have an example of search that has duplicates and where the duplicates are so I can check the full elements?

2021-12-13 13:23 UTC, OlehVeselov92 commented on src/main.js
> +                            uniqueKey : `${Math.random()}${itemId}`, // to have only unique results in dataset => remove Math.Random()
@metalwarrior665 
Understood. Will try to find some examples.

2022-01-04 10:29 UTC, petrpatek requested changes

2022-01-04 10:29 UTC, petrpatek commented on src/main.js
> +                    const maxItemsOnSite = +$('#searchCountPages').text().trim()
The `+` is a bit confusing to me.

2022-01-04 12:06 UTC, metalwarrior665 commented on src/main.js
> +                    const maxItemsOnSite = +$('#searchCountPages').text().trim()
`+` is similat to `Number()` but I also don't like it as it is less expressive and people don't know it that much

2022-01-10 12:10 UTC, OlehVeselov92 commented on src/main.js
> +                    const maxItemsOnSite = +$('#searchCountPages').text().trim()
Agree) Changed it to Number()

2022-01-10 12:23 UTC, merged