updated apify, new proxy config, added sessions
metalwarrior665/actor-indeed-scraper pull request #5
Opened 2020-11-25 11:20 UTC by VaclavRut

2020-11-30 16:25 UTC, metalwarrior665 requested changes

2020-11-30 16:25 UTC, metalwarrior665 commented on INPUT_SCHEMA.json
> +        "proxy":{
This is an un-needed breaking change, please revert this back.

2020-12-03 10:40 UTC, VaclavRut commented on INPUT_SCHEMA.json
> +        "proxy":{
should be reverted

2020-12-04 18:40 UTC, metalwarrior665 approved these changes

2020-12-04 18:40 UTC, merged